"""Parser front-end: Lark + ast_utils → intermediate representation tree."""

from lark import Lark, Transformer, v_args
from lark.ast_utils import create_transformer

from . import _ir


class _ToAst(Transformer):
    """
    Lark transformer.

    Responsibilities:
      1. Convert terminals (STRING, CNAME, INT) to Python types.
      2. Implement rules that have NO matching AST class (transparent helpers).
      3. Implement rules whose AST class needs `attr_clause` stripped before
         construction (binary_expr, group_expr, value_expr, ...).

    The methods defined here override the per-rule methods auto-generated by
    `create_transformer`, so place ONLY those that need custom logic.
    """

    def STRING(self, tok):
        s = str(tok)
        return s[1:-1] if len(s) >= 2 and s[0] == s[-1] == '"' else s

    def CNAME(self, tok):
        return str(tok)

    def INT(self, tok):
        return int(tok)

    def NOT_OP(self, tok):
        return _ir.BoolOp.NOT

    SIGNED_NUMBER = INT

    @v_args(inline=True)
    def boolean_op(self, tok):
        match str(tok):
            case "&":
                return _ir.BoolOp("AND")
            case "|":
                return _ir.BoolOp("OR")
        raise ValueError(f"unsupported boolean operation {tok}")

    @v_args(inline=True)
    def match_type(self, tok):
        return _ir.MatchType(str(tok).lower())

    @v_args(inline=True)
    def output_target(self, tok):
        return _ir.OutputTarget(str(tok).lower())

    @v_args(inline=True)
    def field_name(self, name):
        return name  # already str from CNAME

    @v_args(inline=True)
    def date_between(self, field_tok, _kw, date_lo, date_hi):
        return _ir.DateExpr(
            field=str(field_tok),
            op="between",
            date_lo=str(date_lo),
            date_hi=str(date_hi),
        )

    @v_args(inline=True)
    def date_after(self, field_tok, _kw, date_lo):
        return _ir.DateExpr(field=str(field_tok), op="after", date_lo=str(date_lo))

    @v_args(inline=True)
    def date_before(self, field_tok, _kw, date_hi):
        return _ir.DateExpr(field=str(field_tok), op="before", date_lo=str(date_hi))

    def match_op(self, children):
        """match_op: 'approx' | 'match' match_type"""
        kind = str(children[0]).lower()
        arg = children[1] if len(children) > 1 else None
        return _ir.MatchOp(kind=kind, arg=arg)

    @v_args(inline=True)
    def near_match(self, _near_kw, distance, left, right):
        """near_expr: 'near' '[' SIGNED_NUMBER ']' '(' value_expr ',' value_expr ')'

        Aliased to `near_match` (rather than the auto-derived `near_expr`) so
        that `create_transformer` doesn't clobber this custom method with an
        auto-generated one for the `NearExpr` AST class — mirrors the
        `date_between`/`date_after`/`date_before` pattern used for `date_expr`.
        """
        return _ir.NearExpr(distance=distance, left=left, right=right)

    def compound_expr(self, children):
        node = children[0]
        # If an attr_clause is present, children[1] will be an _ir.AttrClause
        if len(children) > 1:
            attr = children[1]
            if hasattr(node, "fields"):
                node.fields = list(attr.field_list.items)
            else:
                raise ValueError(f"Node {type(node)} does not support fields")
        return node

    @v_args(inline=True)
    def start(self, body):
        return _ir.Query(body=body)


class Parser:
    """Public entry point: `Parser()(text) -> _ir.Query`."""

    def __init__(self, *, debug: bool = False):
        self._lark = Lark.open_from_package(
            __package__,
            "grammar.lark",
            parser="lalr",
            propagate_positions=True,
            maybe_placeholders=False,
            debug=debug,
        )
        # `create_transformer` scans `_ir` for `_Ast` subclasses and generates
        # one method per class; methods we define on `_ToAst` take precedence.
        self._transform = create_transformer(_ir, _ToAst()).transform

    def __call__(self, text: str) -> _ir.Query:
        tree = self.parse_tree(text)
        return self._transform(tree)

    def parse_tree(self, text: str):
        """Return the raw Lark parse tree (debugging aid)."""
        return self._lark.parse(text)
