start: expr
?expr: ( output_spec_expr | compound_expr )


output_spec_expr: "[" "->" output_target ":" compound_expr "]"
!output_target: "query" | "filter"
attr_clause: "in" field_list
field_list: field_name ("," field_name)*

compound_expr: ( group_expr | binary_expr | unary_expr | near_expr | match_expr | date_expr | value_expr ) attr_clause?

date_expr: field_name DATE_BETWEEN STRING "and" STRING   -> date_between
         | field_name DATE_AFTER  STRING                 -> date_after
         | field_name DATE_BEFORE STRING                 -> date_before

DATE_BETWEEN: "between"
DATE_AFTER:   "after"
DATE_BEFORE:  "before"

group_expr: "(" expr ")"
binary_expr: expr boolean_op expr
match_expr: match_op "(" value_expr ")"
near_expr: NEAR "[" SIGNED_NUMBER "]" "(" value_expr "," value_expr ")" -> near_match
unary_expr: NOT_OP value_expr
value_expr: STRING

boolean_op: AND_OP | OR_OP

match_op: APPROX
        | MATCH_LITERAL "[" match_type "]"
APPROX: "approx"
NEAR: "near"
MATCH_LITERAL: "match"
!match_type: "strict" | "loose" | "regex"

AND_OP: "&"
OR_OP: "|"
NOT_OP: "!"

field_name: CNAME

%import common.ESCAPED_STRING -> STRING
%import common.CNAME
%import common.SIGNED_NUMBER
%import common.WS
%ignore WS
