github_url = "https://github.com/koosie0507/mapwisefox"

[version]
current = "0.6.0"

regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "Bump web-frontend to {new_version}"
tag_template = "web-frontend-v{new_version}"

[[file]]
src = "package.json"
search = '"version": "{current_version}"'
