[project]
name = "mapwisefox-kappa-score"
version = "0.1.1"

dependencies = [
    "dedupe>=3.0.3",
    "pandas>=2.3.0",
    "scikit-learn>=1.7.0",
]

[tool.uv]
package = true

[project.scripts]
kappa-score = "mapwisefox.kappa_score:run_command"
