name: Automatic Tagging (release only)

on:
  push:
    branches: [ main ]  # adjust if needed

permissions:
  contents: write  # needed to push tags

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # we need history & tags to avoid duplicates

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Check version & create tag if final
        shell: bash
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: github-actions@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: github-actions@users.noreply.github.com
        run: |
          ver="$(uv tool run bump-my-version show current_version)"
          echo "current_version=$ver"

          # skip if prerelease (contains a dash, e.g., -rc0)
          if [[ "$ver" == *-* ]]; then
            echo "Prerelease detected ($ver); skipping tag."
            exit 0
          fi

          tag="v$ver"

          # Skip if tag already exists
          if git rev-parse -q --verify "refs/tags/$tag" >/dev/null; then
            echo "Tag $tag already exists; skipping."
            exit 0
          else
            make new-tag
          fi
